Ecomerce/Ecomerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("accounts.urls")),
    path("myadmin/",include("myadmin.urls")),
    path("",include("users.urls"))

    

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, documents_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecomerce/myadmin/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.adminlogin,name='adminlogin'),
    path('adminhome/', views.adminhome, name='adminhome'),
    path('sales/',views.sales,name="sales"),
    path('sales_report/<str:format>/', views.sales_report, name='sales_report'),
    path('sales_table/<str:format>/',views.sales_table,name="sales_table"),
    path('charts/', views.charts, name='charts'),
    path('order_chart/', views.order_chart, name='order_chart'),
    path('get_monthly_chart_data/',views.get_monthly_chart_data,name="get_monthly_chart_data"),
    path('get_yearly_chart_data/',views.get_yearly_chart_data,name="get_yearly_chart_data"),
    path('adminlogout',views.adminlogout,name="adminlogout"),
    path('user_management/', views.user_management_view, name='user_management_view'),
    path('edit_user/<int:user_id>/', views.edit_user_view, name='edit_user'),
    path('category_list/', views.category_list, name='category_list'),
    path('category_add/', views.add_category, name='add_category'),
    path('edit-category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete-category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('category/toggle_listing/<int:category_id>/', views.toggle_category_listing, name='toggle_category_listing'),
    path('product/toggle_listing/<int:category_id>/', views.toggle_product_listing, name='toggle_product_listing'),
    path('product_list/', views.product_list, name='product_list'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('add_variant/<int:product_id>/', views.add_variant, name='add_variant'),
    path('delete_product/<int:product_id>/',views.delete_product,name="delete_product"),
    path('admin_orders/', views.admin_orders, name='admin_orders'),
    path('update_order_status/<int:orderid>', views.update_order_status, name='update_order_status'),
    path('add_new_coupon/',views.add_new_coupon,name="add_new_coupon"),
    path('coupon_list/',views.coupon_list,name="coupon_list"),
    path('generate_coupon_code/',views.generate_coupon_code,name="generate_coupon_code"),
    path('add_new_coupon/',views.add_new_coupon,name="add_new_coupon"),
    path('order_view/<str:oid>/',views.admin_order_detail, name="order_view"),
    path('productoffer/',views.productoffer,name="productoffer"),
    path('categoryoffer/',views.categoryoffer,name="categoryoffer"),
    path('add_offer/',views.addoffer,name="add_offer"),
    path('add_category_offer/',views.add_category_offer,name="add_category_offer" ),
    path('adminhome/', views.adminhome, name='adminhome'),
    path('referal/',views.referal,name="referal"),
    path('stock_report/',views.stock_report,name="stock_report"),

] 

Ecomerce/users/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('shop/',views.shop,name="shop"),
    path('c_shop/<str:category>/', views.c_shop, name='c_shop'),
    path('product/<int:product_id>/', views.single_product, name='single_product'),
    path('userprofile/', views.userprofile, name='userprofile'),
    path('search/',views.search_product,name="search"),
    path('search_products/', views.shop_search_products, name='search_products'),
    path('search_products/<str:category>/', views.shop_search_products, name='category_search_products'),
    path('edituser/<int:user_id>/', views.edituser, name='edituser'),
    path('add_address/', views.add_address, name='add_address'),
    path('checkout_address/',views.checkout_address,name="checkout_address"),
    path('remove_address/<int:address_id>/',views.remove_address,name="remove_address"),
    path('edit_address/<int:address_id>/', views.edit_address, name='edit_address'),
    path('get_product_details/<int:colorid>/', views.get_product_details, name='get_product_details'),
    path('get_stock_status/', views.get_stock_status, name='get_stock_status'),
    path('add_to_cart/', views.add_to_cart, name="add_to_cart"),
    path('cartitems_list/',views.cartitems_list,name="cartitems_list"),
    path('wishlist/',views.wishlist,name="wishlist"),
    path('remove_wishlist_item/<int:itemid>/',views.remove_wishlist_item,name="remove_wishlist_item"),
    path('add_to_wishlist/<int:product_id>/<int:variant_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/<int:variant_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('update_cart/<int:item_id>/<int:new_quantity>/', views.update_cart_quantity, name='update_cart'),
    path('remove_cart_item/<int:itemid>/',views.remove_cart_item,name="remove_cart_item"),
    path('cart_order/',views.cart_order,name="cart_order"),
    path('remove_cartorder_item/<int:itemid>/',views.remove_cart_item,name="remove_cartorder_item"),
    path('get_address_details/<int:address_id>/', views.get_address_details, name='get_address_details'),
    path('checkout/', views.checkout,name="checkout"),
    path('razorpay_initiate_payment/', views.initiate_razorpay_payment, name='razorpay_initiate_payment'),
    path('product_checkout/',views.product_checkout,name="product_checkout"),
    path('singleproduct_checkout/',views.singleproduct_checkout,name="singleproduct_checkout"),
    path('product_check/<int:product_id>/<int:color_id>/<int:variant_id>/<int:quantity>/', views.product_check, name="product_check"),
    path('user_orders/',views.user_orders, name="user_orders"),
    path('order_detail/<str:oid>/', views.order_detail,name="order_detail"),
    path('cancel_order/',views.cancel_order, name="cancel_order"),
    path('return/<str:order_id>/',views.o_return, name="o_return"),
    path('order_return/<str:order_id>/',views.order_return,name='order_return'),
    path('generate_invoice_pdf/<int:order_id>/', views.generate_invoice_pdf, name='generate_invoice_pdf'),

    path('wallet/',views.wallet,name="wallet"),
    path('get_coupon_discount/<int:coupon_id>/', views.get_coupon_discount, name='get_coupon_discount'),
]





    

Ecomerce/users/models.py
from django.db import models
from django.db.models import Count, Sum, Case, When, IntegerField
from accounts.models import CustomUser
from myadmin.models import MyProducts,Variant,Color,ProductImages
from django.contrib.auth import get_user_model
from django.utils import timezone
import random
from calendar import month_abbr
from django.db.models import Count, Sum




class Address(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15, default='')
    pincode = models.CharField(max_length=7)
    locality = models.CharField(max_length=255)
    address = models.TextField()
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name} - {self.address}"
    
class cartitems(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(MyProducts, on_delete=models.CASCADE, default=None)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null=True, blank=True)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.PositiveSmallIntegerField()

    @property
    def total_price(self):
        if self.variant is not None:
            if self.variant.discount ==0:
                return self.variant.price * self.quantity
            else:
                return self.variant.discount_price * self.quantity
        else:
            return 0
    @property
    def product_images(self):
        if self.color:
            return ProductImages.objects.filter(product=self.product, color=self.color)
        return None


    
class whishlist(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    product = models.ForeignKey(MyProducts,on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null=True, blank=True)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True)




class MyCoupons(models.Model):
    coupon_code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=255)
    created_date = models.DateTimeField(auto_now_add=True)
    expiry_date = models.DateTimeField()
    min_purchase_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount_price = models.IntegerField()
    is_disabled = models.BooleanField(default=False)


    def is_valid(self):
        if self.expiry_date< timezone.now():
            self.is_disabled=True
            return False
        else:
            return True
        # return not self.is_disabled and timezone.now() < self.expiry_date
    
    def save(self, *args, **kwargs):
        if not self.is_disabled and timezone.now().date() >= self.expiry_date:
            self.is_disabled = True

        super().save(*args, **kwargs)


class UserAppliedCoupon(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    coupon = models.ForeignKey(MyCoupons, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'coupon')



class OrderStatus(models.Model):
    STATUS_CHOICES = [
    ('Pending', 'Pending'),
    ('Shipped', 'Shipped'),
    ('Delivered', 'Delivered'),
    ("Canceled",'Canceled'),
    ('Returned', 'Returned'),
    ('Paid', 'Paid')

    ]
    status = models.CharField(max_length=100, choices=STATUS_CHOICES)

    def __str__(self):
        return self.status


class OrderAddress(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15, default='')
    pincode = models.CharField(max_length=7)
    locality = models.CharField(max_length=255)
    address = models.TextField()
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name} - {self.address}"


class Order(models.Model):
    ORDER_ID_PREFIX = "OID-"
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    coupon = models.ForeignKey(MyCoupons, on_delete=models.CASCADE,default='', null=True,blank=True)
    coupon_code = models.CharField(max_length=100,null=True, blank=True)
    coupon_price = models.DecimalField(max_digits=10, decimal_places=2,null=True, blank=True)
    order_address =models.ForeignKey(OrderAddress,on_delete=models.CASCADE,related_name='orderaddress',null=True, blank=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    discount= models.DecimalField(max_digits=7, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    order_status = models.ForeignKey(OrderStatus, on_delete=models.SET_NULL, null=True)
    payment_status = models.CharField(max_length=10,default='Unpaid')
    payment = models.CharField(max_length=100)
    order_id = models.CharField(max_length=15, unique=True, editable=False)


    def save(self, *args, **kwargs):
        random_code = str(random.randint(1000, 9999))

        if not self.order_id:
            self.order_id = f"{self.ORDER_ID_PREFIX}{random_code}"
        super().save(*args, **kwargs)
    
    # @classmethod
    # def get_daily_orders_chart_data(cls):
    #     today = timezone.now().date()
    #     daily_orders_data = cls.objects.filter(created_at__date=today) \
    #         .values('created_at__hour') \
    #         .annotate(
    #             orders_count=Count('id'),
    #             cancelled_orders_count=Sum(
    #                 Case(
    #                     When(order_status__status='Canceled', then=1),
    #                     default=0,
    #                     output_field=IntegerField()
    #                 )
    #             )
    #         )

    #     hourly_data = [{'hour': i, 'orders_count': 0, 'cancelled_orders_count': 0} for i in range(24)]

    #     for entry in daily_orders_data:
    #         hour = entry['created_at__hour']
    #         index = next((i for i, item in enumerate(hourly_data) if item["hour"] == hour), None)
    #         if index is not None:
    #             hourly_data[index]['orders_count'] = entry['orders_count']
    #             hourly_data[index]['cancelled_orders_count'] = entry['cancelled_orders_count']

    #     return hourly_data

    
    @classmethod
    def get_daily_orders_chart_data(cls):
        today = timezone.now().date()
        daily_orders_data = cls.objects.filter(created_at__date=today) \
            .values('created_at__day') \
            .annotate(
                orders_count=Count('id'),
                cancelled_orders_count=Sum(
                    Case(
                        When(order_status__status='Canceled', then=1),
                        default=0,
                        output_field=IntegerField()
                    )
                )
            )

        daily_data = [{'day': i, 'orders_count': 0, 'cancelled_orders_count': 0} for i in range(1, 32)]

        for entry in daily_orders_data:
            day = entry['created_at__day']
            index = next((i for i, item in enumerate(daily_data) if item["day"] == day), None)
            if index is not None:
                daily_data[index]['orders_count'] = entry['orders_count']
                daily_data[index]['cancelled_orders_count'] = entry['cancelled_orders_count']

        return daily_data

    @classmethod
    def get_daily_orders_count_today(cls):
        today = timezone.now().date()
        return cls.objects.filter(created_at__date=today).count()

    class Meta:
        ordering = ['-created_at', '-id']
        db_table = "Order"
    

    class Meta:
        ordering = ['-created_at', '-id']
        db_table = "Order"

class OrderItem(models.Model):
   variant = models.ForeignKey(Variant, on_delete=models.CASCADE, default=None)
   order = models.ForeignKey(Order, on_delete=models.CASCADE)
   quantity = models.PositiveIntegerField(default=1)
  


class Wallet_user(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2,default = 0)
    payment_type = models.CharField(max_length = 100,null = True)
    user = models.OneToOneField(CustomUser, on_delete = models.CASCADE, related_name = 'wallet',null = True)

class WalletHistory(models.Model):
    TRANSACTION_CHOICES = [
        ('credit', 'Credit'),
        ('debit', 'Debit'),
    ]

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    transaction_type = models.CharField(max_length=10, choices=TRANSACTION_CHOICES)
    date = models.DateTimeField(auto_now_add=True)


class Return(models.Model):

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    reason = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Return #{self.id} - Order #{self.order.id}"
    

class Referral(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    code = models.CharField(max_length=12, blank=True)
    referred_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True, related_name='ref_by')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

Ecomerce/myadmin/templates/myadmin/Coupon_list.html
{% extends 'myadmin/adminbase.html' %}

{% block main %}
 <div class="container">
  <h2>Coupon List</h2>
  
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Coupon Code</th>
        <th scope="col">Name</th>
        <th scope="col">Created Date</th>
        <th scope="col">Expiry Date</th>
        <th scope="col">Minimum Purchase Amount</th>
        <th scope="col">State</th>
        <th scope="col">Discount Price</th>
      </tr>
    </thead>
    <tbody>
      {% for coupon in coupons %}
        <tr>
          <td>{{ coupon.coupon_code }}</td>
          <td>{{ coupon.name }}</td>
          <td>
            {{ coupon.created_date|date:"F j, Y" }}
            </td>
          <td>{{ coupon.expiry_date }}</td>
          <td>{{ coupon.min_purchase_amount }}</td>
          {% if coupon.is_valid %}
          <td>Active</td>
          {% else %}
          <td>Expired</td>
          {% endif %}
          <td>{{ coupon.discount_price }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'add_new_coupon' %}" class="btn btn-primary" >Add Coupon</a>

 </div>
{% endblock %}

Ecomerce/myadmin/templates/myadmin/Create_coupon.html
{% extends 'myadmin/adminbase.html' %}

{% block main %}
  <div class="container mt-5">

    {% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
   {% endfor %}
   
    <h2 class="mb-4">Add Coupon</h2>
    <form method="post" action="{% url 'add_new_coupon' %}">
      {% csrf_token %}
      <div class="mb-3">
        <label for="coupon_code" class="form-label">Coupon Code:</label>
        <div class="input-group">
          <input type="text" class="form-control" name="coupon_code" id="couponCodeInput" value="" required>
          <button type="button" class="btn btn-secondary" onclick="generateCouponCode()">Generate Code</button>
        </div>
      </div>
      <div class="mb-3">
        <label for="name" class="form-label">Name:</label>
        <input type="text" class="form-control" name="name" required>
      </div>
      <div class="mb-3">
        <label for="expiry_date" class="form-label">Expiry Date:</label>
        <input type="date" class="form-control datepicker" name="expiry_date" placeholder="YYYY-MM-DD" autocomplete="off" required>
      </div>
      <div class="mb-3">
        <label for="min_purchase_amount" class="form-label">Minimum Purchase Amount:</label>
        <input type="text" class="form-control" name="min_purchase_amount" required>
      </div>
      <div class="mb-3">
        <label for="discount_percentage" class="form-label">Discount price</label>
        <input type="number" class="form-control" name="discount_price" required>
      </div>
      <button type="submit" class="btn btn-primary">Generate Coupon</button>
    </form>
  </div>
{% endblock %}

{% block script %}
  <script>
    function generateCouponCode() {
      fetch('{% url "generate_coupon_code" %}')
        .then(response => response.json())
        .then(data => {
          document.getElementById('couponCodeInput').value = data.coupon_code;
        })
        .catch(error => console.error('Error:', error));
    }

  </script>
{% endblock %}

Ecomerce/myadmin/templates/myadmin/add_category.html
{% extends 'myadmin/adminbase.html' %}

{% block main %}
<div class="container mt-5">
    <h1>Add Category</h1>
 
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger">
                {{ form.errors }}
            </div>
        {% endif %}
 
        <div class="mb-3">
            <label for="{{ form.name.id_for_label }}" class="form-label">Name</label>
            {{ form.name }}
            {% if form.name.errors %}
                <div class="alert alert-danger">
                   {{ form.name.errors }}
                </div>
            {% endif %}
        </div>
 
        <div class="mb-3">
            <label for="{{ form.description.id_for_label }}" class="form-label">Description</label>
            {{ form.description }}
            {% if form.description.errors %}
                <div class="alert alert-danger">
                   {{ form.description.errors }}
                </div>
            {% endif %}
        </div>
        {% comment %} <div class="mb-3">
            <label for="new_offer_percentage" class="form-label">New Offer Percentage</label>
            <input type="number" class="form-control" name="new_offer_percentage" id="new_offer_percentage" min="0" max="100" step="1" placeholder="Enter offer percentage" required>
         </div>
         
         <div class="mb-3">
            <label for="new_offer_start_date" class="form-label">New Offer Start Date</label>
            <input type="date" class="form-control" name="new_offer_start_date" id="new_offer_start_date" value="{{ date.today }}" placeholder="Select start date" required>
         </div>
         
         <div class="mb-3">
            <label for="new_offer_end_date" class="form-label">New Offer End Date</label>
            <input type="date" class="form-control" name="new_offer_end_date" id="new_offer_end_date" value="{{ date.today }}" placeholder="Select end date" required>
         </div> {% endcomment %}
         
        <div class="mb-3">
            <label for="{ { form.image.id_for_label }}" class="form-label">Image</label>
            {{ form.image }}
            {% if form.image.errors %}
                <div class="alert alert-danger">
                   {{ form.image.errors }}
                </div>
            {% endif %}
        </div>
 
        <button type="submit" class="btn btn-primary">Add Category</button>
    </form>
 
    <a href="{% url 'category_list' %}" class="btn btn-secondary mt-3">Back to Category List</a>
 </div>
 
{% endblock %}

{% block script %}
<script>
    function validateDates() {
        var startDateInput = document.getElementById('new_offer_start_date');
        var endDateInput = document.getElementById('new_offer_end_date');

        var startDate = new Date(startDateInput.value);
        var endDate = new Date(endDateInput.value);

        var today = new Date();

        if (startDate < today) {
            alert('Start date must not be before today.');
            return false;
        }

        if (endDate < startDate) {
            alert('End date must not be before the start date.');
            return false;
        }

        return true;
    }

    document.getElementById('submit_button_id').addEventListener('click', function(event) {
        if (!validateDates()) {
            event.preventDefault();  // Prevent form submission if validation fails
        }
    });
</script>
{% endblock %}

Ecomerce/myadmin/templates/myadmin/admin_pdf_salesreport.html
<!DOCTYPE html>
<html>
<head>
   <title>Sales Report</title>
   <style>
       body {
           font-family: Arial, sans-serif;
       }
       table {
           width: 100%;
           border-collapse: collapse;
       }
       th, td {
           border: 1px solid #000;
           padding: 8px;
           text-align: left;
       }
       th {
           background-color: #f2f2f2;
       }
   </style>
</head>
<body>
   <h1>Sales Report</h1>
   <table>
       <thead>
           <tr>
               <th>ID</th>
               <th>Order Date</th>
               <th>Products</th>
               <th>User</th>
               <th>Price</th>
               <th>Quantity</th>
               <th>Payment Method</th>
           </tr>
       </thead>
       <tbody>
           {% for order in orders %}
                <tr>
                    <td>{{ order.order_id }}</td>
                    <td>{{ order.created_at }}</td>
                    <td>
                        {% for item in order.orderitem_set.all %}
                            {{ item.variant.product_id.name }},
                        {% endfor %}
                    </td>
                    <td>{{ order.user.name }}</td>
                    <td>{{ order.total_price }}</td>
                    <td>{{ order.orderitem_set.count }}</td>
                    <td>
                        {% if order.payment == 'COD' %}
                            Cash on Delivery
                        {% elif order.payment == 'online' %}
                            Online Payment
                        {% else %}
                            Wallet
                        {% endif %}
                    </td>
                </tr>
           {% endfor %}
       </tbody>
   </table>
</body>
</html>

Ecomerce/myadmin/templates/myadmin/edituser.html
{% extends "myadmin/adminbase.html" %}

{% block title %}Edit User{% endblock %}

{% block main %}
 <div class="bg-white container">
   <div class="jumbotron">
       <h1 class="display-4">Edit User</h1>
       <form method="POST">
           {% csrf_token %}
           <label for="name">Name:</label>
           <input type="text" id="name" name="name" value="{{ user.name }}" required>
           <label for="email">Email:</label>
           <input type="email" id="email" name="email" value="{{ user.email }}" required>
           <label for="phone_number">Phone Number:</label>
           <input type="tel" id="phone_number" name="phone_number" value="{{ user.phone_number }}">
           <input type="submit" value="Save">
       </form>
   </div>
 </div>
{% endblock %}

Ecomerce/myadmin/templates/myadmin/pdf_preview.html
<!DOCTYPE html>
<html>
<head>
   <title>Sales Report</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
   <style>
       body {
           font-family: Arial, sans-serif;
       }
       table {
           width: 100%;
           border-collapse: collapse;
       }
       th, td {
           border: 1px solid #000;
           padding: 8px;
           text-align: left;
       }
       th {
           background-color: #f2f2f2;
       }
   </style>
</head>
<body>
   <h1>Sales Report</h1>
   <p> {{start_date}} to {{end_date}} </p>
   <table>
       <thead>
           <tr>
               <th>ID</th>
               <th>Order Date</th>
               <th>Products</th>
               <th>User</th>
               <th>Price</th>
               <th>Quantity</th>
               <th>Payment Method</th>
           </tr>
       </thead>
       <tbody>
           {% for order in orders %}
                <tr>
                    <td>{{ order.order_id }}</td>
                    <td>{{ order.created_at }}</td>
                    <td>
                        {% for item in order.orderitem_set.all %}
                            {{ item.variant.product_id.name }},
                        {% endfor %}
                    </td>
                    <td>{{ order.user.name }}</td>
                    <td>{{ order.total_price }}</td>
                    <td>{{ order.orderitem_set.count }}</td>
                    <td>
                        {% if order.payment == 'COD' %}
                            Cash on Delivery
                        {% elif order.payment == 'online' %}
                            Online Payment
                        {% else %}
                            Wallet
                        {% endif %}
                    </td>
                </tr>
           {% endfor %}
       </tbody>
   </table>


</div>
{% if format == 'pdf' %}
<form method="get" action="{% url 'sales_report' format=format %}" class="mt-4 ms-4">
    {% csrf_token %}

      <input type="hidden"  name="start_date" value="{{start_date}}">

      <input type="hidden"  name="end_date" value="{{end_date}}">

    <button type="submit" class="btn btn-primary">Generate PDF Report</button>
  </form>
{% else  %}
<form method="get" action="{% url 'sales_report' format=format %}" class="mt-4 ms-4">
    {% csrf_token %}

      <input type="hidden"  name="start_date" value="{{start_date}}">

      <input type="hidden"  name="end_date" value="{{end_date}}">

    <button type="submit" class="btn btn-success">Generate Excel Report</button>
  </form>
{% endif %}

<a href="{% url "sales" %}" class="btn btn-info mt-3 ms-4">Back</a>
</body>


</html>