Ecomerce/Ecomerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("accounts.urls")),
    path("myadmin/",include("myadmin.urls")),
    path("",include("users.urls"))

    

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, documents_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecomerce/users/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('shop/',views.shop,name="shop"),
    path('c_shop/<str:category>/', views.c_shop, name='c_shop'),
    path('product/<int:product_id>/', views.single_product, name='single_product'),
    path('userprofile/', views.userprofile, name='userprofile'),
    path('search/',views.search_product,name="search"),
    path('search_products/', views.shop_search_products, name='search_products'),
    path('search_products/<str:category>/', views.shop_search_products, name='category_search_products'),
    path('edituser/<int:user_id>/', views.edituser, name='edituser'),
    path('add_address/', views.add_address, name='add_address'),
    path('checkout_address/',views.checkout_address,name="checkout_address"),
    path('remove_address/<int:address_id>/',views.remove_address,name="remove_address"),
    path('edit_address/<int:address_id>/', views.edit_address, name='edit_address'),
    path('get_product_details/<int:colorid>/', views.get_product_details, name='get_product_details'),
    path('get_stock_status/', views.get_stock_status, name='get_stock_status'),
    path('add_to_cart/', views.add_to_cart, name="add_to_cart"),
    path('cartitems_list/',views.cartitems_list,name="cartitems_list"),
    path('wishlist/',views.wishlist,name="wishlist"),
    path('remove_wishlist_item/<int:itemid>/',views.remove_wishlist_item,name="remove_wishlist_item"),
    path('add_to_wishlist/<int:product_id>/<int:variant_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/<int:variant_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('update_cart/<int:item_id>/<int:new_quantity>/', views.update_cart_quantity, name='update_cart'),
    path('remove_cart_item/<int:itemid>/',views.remove_cart_item,name="remove_cart_item"),
    path('cart_order/',views.cart_order,name="cart_order"),
    path('remove_cartorder_item/<int:itemid>/',views.remove_cart_item,name="remove_cartorder_item"),
    path('get_address_details/<int:address_id>/', views.get_address_details, name='get_address_details'),
    path('checkout/', views.checkout,name="checkout"),
    path('razorpay_initiate_payment/', views.initiate_razorpay_payment, name='razorpay_initiate_payment'),
    path('product_checkout/',views.product_checkout,name="product_checkout"),
    path('singleproduct_checkout/',views.singleproduct_checkout,name="singleproduct_checkout"),
    path('product_check/<int:product_id>/<int:color_id>/<int:variant_id>/<int:quantity>/', views.product_check, name="product_check"),
    path('user_orders/',views.user_orders, name="user_orders"),
    path('order_detail/<str:oid>/', views.order_detail,name="order_detail"),
    path('cancel_order/',views.cancel_order, name="cancel_order"),
    path('return/<str:order_id>/',views.o_return, name="o_return"),
    path('order_return/<str:order_id>/',views.order_return,name='order_return'),
    path('generate_invoice_pdf/<int:order_id>/', views.generate_invoice_pdf, name='generate_invoice_pdf'),

    path('wallet/',views.wallet,name="wallet"),
    path('get_coupon_discount/<int:coupon_id>/', views.get_coupon_discount, name='get_coupon_discount'),
]





    

Ecomerce/myadmin/models.py
from decimal import Decimal
from django.db import models
from accounts.models import CustomUser
from colorfield.fields import ColorField
from django.utils import timezone

class BlockedUser(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='blocked_user')

    def __str__(self):
        return self.user.email


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='category/', blank=True)
    is_listed = models.BooleanField(default=True)

    def __str__(self):
        return self.name
class Color(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
class MyProducts(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    category= models.ForeignKey(Category, on_delete=models.CASCADE)
    is_listed = models.BooleanField(default=True)


    def __str__(self):
        return self.name

class Variant(models.Model):
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    product_id = models.ForeignKey(MyProducts, on_delete=models.CASCADE, default=None)
    stock_added=models.IntegerField(default=0)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price=  models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount= models.DecimalField(max_digits=5, decimal_places=2, default=0)
    is_listed = models.BooleanField(default=True)

    def get_discount(self):
        if self.discount != 0:
            return self.price - (self.price * Decimal((self.discount / 100)))
        else:
            return self.price
    

class ProductImages(models.Model):
    image = models.ImageField(upload_to='product_images/')
    product = models.ForeignKey(MyProducts, on_delete=models.CASCADE, default=None)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, related_name='images', null=True, blank=True)
    
    def __str__(self):
        return f"{self.color.name}"

class ProductOffer(models.Model):
    product = models.ForeignKey('MyProducts', on_delete=models.CASCADE)
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.product.name} - {self.discount_percentage}% Off"

class CategoryOffer(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.category.name} - {self.discount_percentage}% Off"

Ecomerce/users/views.py
from datetime import datetime, date
from django.core.validators import validate_email, RegexValidator
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from datetime import date
from django.utils import timezone
from django.urls import reverse
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json
from django.http import Http404
from django.http import HttpResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from reportlab.pdfgen import canvas
from io import BytesIO
from myadmin.models import BlockedUser
from myadmin.models import Category,ProductImages,MyProducts, Variant, Color,CategoryOffer,ProductOffer
from users.models import Address,cartitems,Order, OrderItem,OrderStatus,whishlist,OrderAddress,Wallet_user, WalletHistory,Return,MyCoupons,UserAppliedCoupon,Referral
from accounts.models import CustomUser
from django.contrib import messages
from django.core import signing 
from django.views.decorators.cache import cache_control
from django.contrib.auth.decorators import login_required
from django.core.exceptions import MultipleObjectsReturned
from django.core.exceptions import ObjectDoesNotExist
from decimal import Decimal, ROUND_DOWN
import razorpay
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from io import BytesIO



def apply_category_offer(product, category_offers):
    if product.category.id in category_offers:
        offer_percentage = category_offers[product.category.id]
        if offer_percentage is not None:
            first_variant = product.variant_set.first()
            if first_variant:
                original_price = first_variant.price
                discounted_price = original_price - (original_price * (Decimal(offer_percentage) / 100))
                return {
                    'original_price': original_price,
                    'discounted_price': discounted_price,
                    'discount_percentage': offer_percentage
                }
    return None



def cart_count(request):
   if request.user.is_authenticated:
       bag_count = cartitems.objects.filter(user=request.user).count()
   else:
       bag_count = 0
   return {'bag_count': bag_count}


def single_product(request,product_id):
    product = get_object_or_404(MyProducts, pk=product_id)
    variant = Variant.objects.filter(product_id=product_id)[0]
    images= ProductImages.objects.filter(color_id = variant.color.id)
    try:
        category_offer = CategoryOffer.objects.filter(category=product.category, end_date__gte=timezone.now().date()).first()
        Productofferprice = variant.price - (variant.price * (category_offer.discount_percentage / 100))
    except:
        Productofferprice=None
        category_offer=None

    if Productofferprice:
        context={
            'product':product,
            'variant':variant,
            'images':images,
            'category_offer':category_offer,
            'Productofferprice':Productofferprice,
        }
    else:
        context={
            'product':product,
            'variant':variant,
            'images':images,
        }

    return render(request, 'users/singleproduct.html', context)



# def get_product_images(request):
#     product_id = request.GET.get('product_id')
#     color = request.GET.get('color')

#     color_instance = get_object_or_404(Color, name=color)
#     product_images = ProductImages.objects.filter(product_id=product_id, color=color_instance)

#     data = {
#         'images': [{'image_url': img.image.url} for img in product_images],
#     }

#     return JsonResponse(data)

def search_product(request):
  if request.method == "POST":
      query_name = request.POST.get('name', None)
      if query_name:
          results = MyProducts.objects.filter(name__icontains=query_name)
          if results:
              product = results[0]
              return redirect('single_product', product_id=product.pk)
          
  messages.warning(request,"No such product found !")  
  return redirect('home')


def shop_search_products(request,category=None):
    if request.method == 'GET':
        search_term = request.GET.get('search_term', '')
        if category:
            category_obj = get_object_or_404(Category, name=category)
            products = MyProducts.objects.filter(category=category_obj, name__icontains=search_term)
        else:
            products = MyProducts.objects.filter(name__icontains=search_term)
        
        
        product_list = []
        for product in products:

            image = ProductImages.objects.filter(product=product).first()
            first_variant = Variant.objects.filter(product_id=product).first()
            if image:
                product_data = {

                    'id': product.id,
                    'name': product.name,
                    'image': image.image.url,
                    'price': first_variant.price,

                }
                product_list.append(product_data)

        return JsonResponse({'products': product_list})

    
def category_search_products(request):
        if request.method == 'GET':
            search_term = request.GET.get('search_term', '')
            products = MyProducts.objects.filter(name__icontains=search_term)
            
        
        product_list = []
        for product in products:
            # Get the first image for each product (you might want to adjust this logic)
            image = ProductImages.objects.filter(product=product).first()
            first_variant = Variant.objects.filter(product_id=product).first()
            if image:
                product_data = {

                    'id': product.id,
                    'name': product.name,
                    'image': image.image.url,
                    'price': first_variant.price
                }
                product_list.append(product_data)

        return JsonResponse({'products': product_list})


def get_product_details(request,colorid):
    try:
        variant = Variant.objects.get(color_id=colorid)
        images= ProductImages.objects.filter(color_id=variant.color.id)
        images = [{'image': img.image.url} for img in images]
        data = {
            'variant': {
                'price': variant.price,
                'variant_id':variant.id,
                'color_id':colorid,
                'discount':variant.discount,
                'discount_price':variant.discount_price,
                'quantity': variant.quantity,
            },
            'images': images,
        }
        return JsonResponse(data)
    
    except Variant.DoesNotExist:
        return JsonResponse({'error': 'Variant not found'}, status=404)
    except ProductImages.DoesNotExist:
        return JsonResponse({'error': 'Product images not found'}, status=404)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)  



def get_stock_status(request):
    color_id = request.GET.get('colorid')
    quantity = request.GET.get('quantity')
    print(color_id, quantity)
    variant = Variant.objects.get(color_id=color_id)
    print(variant.quantity)
    stock= variant.quantity
    out_of_stock=None

    if int(quantity) > stock:
        print(True)
        out_of_stock = True

    data = {
        'outOfStock': out_of_stock,
    }

    return JsonResponse(data)


def shop(request):
    if not request.user.is_authenticated:
        return redirect('signup')

    products = MyProducts.objects.all()
    images = ProductImages.objects.all()
    sort_option = request.GET.get('sort', 'default')
    price_range = request.GET.get('price_range', 'all')
    is_filter= request.GET.get('filter')
    is_sort = request.GET.get('sort')
    print(is_filter)

    if sort_option == 'low_to_high':
        products = products.order_by('variant__price')
    elif sort_option == 'high_to_low':
        products = products.order_by('-variant__price')

    products_500_1000 = products.filter(variant__price__gte=500, variant__price__lte=1000)
    products_1000_2000 = products.filter(variant__price__gt=1000, variant__price__lte=2000)
    products_2000_ = products.filter( variant__price__gt=2000)

    if sort_option == 'low_to_high':
        products_500_1000 = products_500_1000.order_by('variant__price')
        products_1000_2000 = products_1000_2000.order_by('variant__price')
    elif sort_option == 'high_to_low':
        products_500_1000 = products_500_1000.order_by('-variant__price')
        products_1000_2000 = products_1000_2000.order_by('-variant__price')

    if price_range == '500_1000':
        print("500")
        if products_500_1000.exists(): 
            products = products_500_1000
            print(products)
        else:

            products = MyProducts.objects.none()
            return render(request, 'users/shop.html', {'products': products,})

    elif price_range == '1000_2000':
        if products_1000_2000.exists():
            products = products_1000_2000
        else:
            products = MyProducts.objects.none()
            return render(request, 'users/shop.html', {'products': products,})

    elif price_range == '2000_':
        if products_2000_.exists():
            products = products_2000_
        else:
            products=MyProducts.objects.none()
            return render(request, 'users/shop.html', {'products': products,})
    

    elif price_range == 'all':
        if sort_option == 'low_to_high':
            products = products.order_by('variant__price')
        elif sort_option == 'high_to_low':
            products = products.order_by('-variant__price')
    

Ecomerce/users/templates/users/add_address.html
{% extends "users/ubase.html" %}

{% block main %}
  <div class="container mt-4">
    {% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
   {% endfor %}


    <h2>Add Address</h2>
    <form method="post" action="{% url 'add_address' %}" onsubmit="return validateForm()" >
      {% csrf_token %}
      
      <div class="mb-3">
        <label for="name" class="form-label">Name:</label>
        <input type="text" class="form-control" id="name" name="name" required>
        <span id="nameError" style="color: red;"></span><br>
      </div>
      
      <div class="mb-3">
        <label for="phone" class="form-label">Phone Number:</label>
        <input type="text" class="form-control" id="phone" name="phone" required>
        <span id="phoneError" style="color: red;"></span><br>
      </div>
      
      <div class="mb-3">
        <label for="pincode" class="form-label">Pincode:</label>
        <input type="text" class="form-control" id="pincode" name="pincode" required>
        <span id="pincodeError" style="color: red;"></span><br>

      </div>
      
      <div class="mb-3">
        <label for="locality" class="form-label">Locality:</label>
        <input type="text" class="form-control" id="locality" name="locality" required>
        <span id="localityError" style="color: red;"></span><br>

      </div>
      
      <div class="mb-3">
        <label for="address" class="form-label">Address:</label>
        <input type="text" class="form-control" id="address" name="address" required>
        <span id="addressError" style="color: red;"></span><br>
  
      </div>
      
      <div class="mb-3">
        <label for="city" class="form-label">City:</label>
        <input type="text" class="form-control" id="city" name="city" required>
        <span id="cityError" style="color: red;"></span><br>  
      </div>
      
      <div class="mb-3">
        <label for="state" class="form-label">State:</label>
        <input type="text" class="form-control" id="state" name="state" required>
        <span id="stateError" style="color: red;"></span><br>
      </div>
      
      <button type="submit" class="btn btn-primary">Add Address</button>
    </form>
  </div>
{% endblock %}



{% block script %}
<script>
  function validateForm() {
    var name = document.getElementById('name').value;
    var phone = document.getElementById('phone').value;
    var pincode = document.getElementById('pincode').value;
    var locality = document.getElementById('locality').value;
    var address = document.getElementById('address').value;
    var city = document.getElementById('city').value;
    var state = document.getElementById('state').value;

    var nameError = document.getElementById('nameError');
    var phoneError = document.getElementById('phoneError');
    var pincodeError = document.getElementById('pincodeError');
    var localityError = document.getElementById('localityError');
    var addressError = document.getElementById('addressError');
    var cityError = document.getElementById('cityError');
    var stateError = document.getElementById('stateError');

    nameError.innerHTML = '';
    phoneError.innerHTML = '';
    pincodeError.innerHTML = '';
    localityError.innerHTML = '';
    addressError.innerHTML = '';
    cityError.innerHTML = '';
    stateError.innerHTML = '';

    var isValid = true;

    // Basic validation for name
    if (name.trim() === '') {
      nameError.innerHTML = 'Name is required.';
      isValid = false;
    }

    // Basic validation for phone
    if (!/^[6-9]\d{9}$/.test(phone)) {
      phoneError.innerHTML = 'Invalid phone number format. Example: 9876543210';
      isValid = false;
    }

    // Validation for PIN code
    if (!/^\d{6}$/.test(pincode)) {
      pincodeError.innerHTML = 'PIN code must be a 6-digit number.';
      isValid = false;
    }

    // Additional validation for locality, address, city, state (you can customize this)
    if (locality.trim() === '') {
      localityError.innerHTML = 'Locality is required.';
      isValid = false;
    }

    if (address.trim() === '') {
      addressError.innerHTML = 'Address is required.';
      isValid = false;
    }

    if (city.trim() === '') {
      cityError.innerHTML = 'City is required.';
      isValid = false;
    }

    if (state.trim() === '') {
      stateError.innerHTML = 'State is required.';
      isValid = false;
    }

    return isValid;
  }
</script>

{% endblock %}

Ecomerce/users/templates/users/shop.html
{% extends "users/ubase.html" %}
{% load static %}

{% block css %}
<style>
    .container {
        margin-top: 8px;
    }

    .filter-container {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .filter {
        display: flex;
        align-items: center;
    }

    select {
        width: 150px;
        padding: 10px;
        border: none;
        border-radius: 4px;
        background-color: #f1f1f1;
        font-size: 16px;
        margin-right: 10px;
    }

    .Apply {
        background-color: grey;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        cursor: pointer;
    }

    .Apply:hover {
        opacity: 0.8;
        border: 1px solid black;
    }

    #searchInput {
        padding: 10px;
        border: none;
        border-radius: 4px;
        background-color: #f1f1f1;
        font-size: 16px;
        width: 300px;
    }

    #searchButton {
        background-color: grey;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        cursor: pointer;
    }

    #searchButton:hover {
        opacity: 0.8;
        border: 1px solid black;
    }

    .product-card {
        margin-bottom: 20px;
    }
</style>

<link rel="stylesheet" href="{% static "css/hstyle.css" %}">
{% endblock %}

{% block main %}
<div class="container">
    <h2 class="text-center m-3">Our Products</h2>
    
    <div class="filter-container">
        {% if category %}
        <form class="filter mb-2" method="get" action="{% url 'c_shop' category.name %}">
        {% else %}
        <form class="filter mb-2" method="get" action="{% url 'shop' %}">
        {% endif %}
        <input type="hidden" value="{{filter}}">
            <select name="sort">
                
                <option value="default">Default</option>
                <option value="low_to_high">Low to High Price</option>
                <option value="high_to_low">High to Low Price</option>
            </select>
            <button class="btn Apply" type="submit">Apply</button>

        </form>

        {% if category %}
        <form class="filter mb-2" method="get" action="{% url 'c_shop' category.name %}">
        {% else %}
        <form class="filter mb-2" method="get" action="{% url 'shop' %}">
        {% endif %}
        <div class="filter">
            <input type="hidden" value="{{sort}}">
            <select name="price_range">
                <option value="all">All Prices</option>
                <option value="500_1000">Rs. 500 - Rs. 1000</option>
                <option value="1000_2000">Rs. 1000 - Rs. 2000</option>
                <option value="2000_">Price >2000</option>
                <!-- Add more options as needed -->
            </select>
            <button class="btn Apply" type="submit">Apply</button>
        </div>
        </form>

        <div class="search-container">
            <input type="text" id="searchInput" placeholder="Search products...">
        </div>
    </div>


    {% if products %}
    <div class="row mt-4 " id="productContainer">
        
        <!-- Product 1 -->
        {% for product in products %}
        <div class="col-md-4 mb-4">
            {% if product.category.is_listed == False %}
            <div class="product-card">
                {% with first_variant=product.variant_set.first %}
                    {% if first_variant %}
                <button class="wishlist-btn" onclick="toggleWishlist(this, {{ product.id }}, {{ first_variant.id }})">
                    <i class="far fa-heart"></i>
                </button>
                {% endif %}
                {% endwith %}
                    
                <a href="{% url 'single_product' product_id=product.id %}" class="prod-det">
                {% for img in product.productimages_set.all %}
                {% if forloop.first %}
                  <!-- Display only the first image with a responsive class -->
                  <img src="{{ img.image.url }}" alt="{{ product.name }}" class="product-img img-fluid">
                {% endif %}
              {% endfor %}</a>
                
                <div class="product-info">
                    {% comment %} <div class="rating-box">4.1<i class="fas fa-star"></i></div> {% endcomment %}
                    <h5 class="product-name"> {{product.name}} </h5>
                    {% with first_variant=product.variant_set.first %}
                    {% if first_variant %}
                    {% if first_variant.discount != 0 %}
                    <p class="product-price">Price: <strike>{{ first_variant.price }}</strike></p>
                    <span class="text-danger me-3" style="font-size: large;">{{ first_variant.discount }}%</span><span class="product-price">{{ first_variant.discount_price }}</span>
                    {% else %}
                    <p class="product-price">Price: {{ first_variant.price }}</p>
                        {% endif %}
    
                    {% endif %}
                    {% endwith %}
                </div>
              
            </div>
        </div>
        {% endif %}
        {% endfor %}
   </div>
   {% else %}
    <div style="height: 80vh;">
    <p class="no-products-message">No products found in the specified price range.</p>
    </div>
    {% endif %}

</div>
{% endblock main %}

{% block script %}


<script>
    const referenceProductURL = "{% url 'single_product' product_id=0 %}"
    function toggleWishlist(button, productId, variantId) {
        button.classList.toggle('wishlist-selected');
        console.log("Hellooo!!");
        const csrftoken = getCookie('csrftoken');

        const action = button.classList.contains('wishlist-selected') ? 'add' : 'remove';

        let url, method;
        if (action === 'add') {
            url = `/add_to_wishlist/${productId}/${variantId}/`;
            method = 'POST';
        } else {
            url = `/remove_from_wishlist/${productId}/${variantId}/`;
            method = 'POST';
        }

        fetch(url, {
                method: method,
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken
                },
                body: JSON.stringify({})
            })
            .then(response => response.json())
            .then(data => {
                showAlert(data.status, data.message);
                if (data.status === 'added') {
                    console.log('Added to wishlist');
                } else if (data.status === 'removed') {
                    console.log('Removed from wishlist');
                } else if (data.status === 'already_added') {
                    console.log('Already in wishlist');
                } else if (data.status === 'not_in_wishlist') {
                    console.log('Not in wishlist');
                }

            })
            .catch(error => {
                console.error('Error:', error);
            });

    }

    function showAlert(status, message) {
        Swal.fire({
            icon: status === 'added' || status === 'removed' ? 'success' : 'info',
            title: 'Wishlist',
            text: message,
            showConfirmButton: false,
            timer: 1500
        });
    }


    // Function to get the CSRF token from the cookie
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }

    const searchInput = document.getElementById('searchInput');
    const productContainer = document.getElementById('productContainer');

    searchInput.addEventListener('input', function () {
        const searchTerm = searchInput.value;
        const category = '{{ category.name }}'; // Get the category name from the template
        const url = category ? `/search_products/${category}/?search_term=${searchTerm}` : `/search_products/?search_term=${searchTerm}`;
    
        fetch(url)
            .then(response => response.json())
            .then(data => updateProductList(data.products
            ))
            .catch(error => console.error('Error:', error));
    });

    function updateProductList(products) {


        productContainer.innerHTML = '';
        if (products.length > 0) {
            products.forEach(product => {
                console.log(product.id)

                if (product.id) { 
                    const prodURL = referenceProductURL.replace('0', product.id.toString());
                const productCard = `
                        <div class="col-md-4 mb-4">
                            <div class="product-card">
                                <button class="wishlist-btn" onclick="toggleWishlist(this, ${product.id}, ${product.variant_id})">
                                    <i id="heartIcon" class="far fa-heart"></i>
                                </button>
                                <a href="${prodURL}" class="prod-det">                                    <img src="${product.image}" alt="${product.name}" class="product-img img-fluid">
                                </a>
                                <div class="product-info">
                                    <h5 class="product-name">${product.name}</h5>
                                    <p class="product-price">Price: ${product.price}</p>
                                </div>
                            </div>
                        </div>
                    `;

                productContainer.innerHTML += productCard;
                    }
            });
        } else {
            // Display a message when no products are found
            productContainer.innerHTML = '<h2 style="height:100vh;">No products found</h2>';
        }
    }


</script>
{% endblock %}